### ISSUE TITLE
Path to disk

### ISSUE THREAD

**Issue by vivekzhere** [xosnitc/xsm#5]
The path to disk file is currently relative to the location from which program is invoked. this is creating problems.

**Comment by jasper-lyons** [comment]
+1

I'm having fun playing with the eXOS project but this is pretty annoying, especially as the download link for the .tar.gz is dead: http://xosnitc.github.io/usage-spec.html#navsetup

Whats the status? Has it been abandoned?

**Comment by shamilcm** [comment]
Thanks for pointing out the issue. Its now fixed. The project is not abandoned, its still actively used and developed. Please report issues you find as 'New Issue'. Also, you may subscribe to the user mailing list in case you have queries on using it.
